default_models:
  global_default: "Claude 3.7 Sonnet"
  anthropic: "Claude 3.7 Sonnet"
  openai: "GPT-4o"
  bedrock: "Llama 3.3 70B Instruct"

models:
    
  ### ANTHROPIC MODEL CONFIG -- REROUTING THROUGH BEDROCK ASYNC
  anthropic:
    "Anthropic Claude 3.7 Sonnet":
      # model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      model_id: "claude-3-7-sonnet-20250219"
      input_token_cost: 0.000003 # $0.003/1K tokens
      output_token_cost: 0.000015 # $0.015/1K tokens
      context_length: 200000
      max_tokens: 8192
    "Anthropic Claude 3.5 Sonnet":
      # model_id: "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
      model_id: "claude-3-5-sonnet-20241022"
      input_token_cost: 0.000003 # $0.003/1K tokens
      output_token_cost: 0.000015 # $0.015/1K tokens
      context_length: 200000
      max_tokens: 8192
    "Anthropic Claude 3.5 Haiku":
      # model_id: "us.anthropic.claude-3-5-haiku-20241022-v1:0"
      model_id: "claude-3-5-haiku-20241022"
      input_token_cost: 0.0000008 # $0.0008/1K tokens
      output_token_cost: 0.000004 # $0.004/1K tokens
      context_length: 200000
      max_tokens: 8192
      
  ### OPENAI MODEL CONFIG
  openai:
    "GPT-4o":
      model_id: "gpt-4o-2024-11-20"
      input_token_cost: 0.0000025 # $2.50/1M tokens
      output_token_cost: 0.00001 # $10/1M tokens
      context_length: 128000
      max_tokens: 16384
    "GPT-4o-mini":
      model_id: "gpt-4o-mini-2024-07-18"
      input_token_cost: 0.00000015 # $0.15/1M tokens
      output_token_cost: 0.0000006 # $0.60/1M tokens
      context_length: 128000
      max_tokens: 16384

  ### BEDROCK MODEL CONFIG
  bedrock:
    "Llama 3.3 70B Instruct":
      model_id: "us.meta.llama3-3-70b-instruct-v1:0"
      input_token_cost: 0.00000072 # $0.00072/1K tokens
      output_token_cost: 0.00000072 # $0.00072/1K tokens
      context_length: 128000
      max_tokens: 2048
    "Claude 3.7 Sonnet":
      model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      input_token_cost: 0.000003 # $0.003/1K tokens
      output_token_cost: 0.000015 # $0.015/1K tokens
      context_length: 200000
      max_tokens: 8192
    "Claude 3.5 Sonnet":
      model_id: "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
      input_token_cost: 0.000003 # $0.003/1K tokens
      output_token_cost: 0.000015 # $0.015/1K tokens
      context_length: 200000
      max_tokens: 8192
    "Claude 3.5 Haiku":
      model_id: "us.anthropic.claude-3-5-haiku-20241022-v1:0"
      input_token_cost: 0.0000008 # $0.0008/1K tokens
      output_token_cost: 0.000004 # $0.004/1K tokens
      context_length: 200000
      max_tokens: 8192

### INFERENCE REFERENCES
# CLAUDE: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-claude.html
# META: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-meta.html
# PRICING: https://aws.amazon.com/bedrock/pricing/
