name: build-what-lives
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/**
  # Allow manual triggering
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: whatlives
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Get current date for tagging
      - name: Get the current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> ${GITHUB_ENV}
      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      # Build and push what lives environment to GHCR
      - name: Build and Push Server Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: environment/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main-${{ env.CURRENT_DATE }}
          cache-from: |
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:main
          cache-to: |
            type=inline
